services:
- type: web
  name: BeWell-AI
  env: python
  buildCommand: |
    pip install --upgrade pip
    pip install -r requirements.txt
  startCommand: gunicorn app:app --workers 1 --bind 0.0.0.0:$PORT --max-requests 1000 --max-requests-jitter 100 --timeout 120
