services:
- type: web
  name: BeWell-AI
  env: python
  buildCommand: |
    pip install --upgrade pip setuptools wheel
    pip install -r requirements.txt

  startCommand: |
    export PYTHONUNBUFFERED=1
    export PYTHONDONTWRITEBYTECODE=1
    export TOKENIZERS_PARALLELISM=false
    gunicorn app:app --workers 1 --threads 2 --bind 0.0.0.0:$PORT --max-requests 500 --timeout 120 --worker-class sync --worker-tmp-dir /dev/shm --preload

