services:
  - type: web
    name: BeWell-AI
    env: python
    runtime: python-3.10.12
    buildCommand: |
      # Install only production requirements
      ./build.sh
      
    startCommand: |
      # Set memory-optimized environment variables
      export PYTHONUNBUFFERED=1
      export PYTHONDONTWRITEBYTECODE=1
      export TOKENIZERS_PARALLELISM=false
      
      # Start with single worker and memory limits
      gunicorn app:app \
        --workers 1 \
        --threads 2 \
        --bind 0.0.0.0:$PORT \
        --max-requests 500 \
        --max-requests-jitter 50 \
        --timeout 120 \
        --worker-class sync \
        --worker-tmp-dir /dev/shm \
        --preload

    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12